import { useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import Svg, { Defs, LinearGradient, Path, Stop } from 'react-native-svg';
import { Screen } from '@/components/ui';
import { useChronosData } from '@/features/app/useChronosData';
import { radius, spacing, useTheme } from '@/theme/tokens';

const metrics = ['Продуктивность', 'Время', 'Цели', 'Баланс'] as const;
export default function AnalyticsScreen() {
  const { colors } = useTheme(); const data = useChronosData(); const [metric, setMetric] = useState<(typeof metrics)[number]>('Время');
  const week = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index)); const seconds = data.sessions.filter((session) => new Date(session.started_at).toDateString() === date.toDateString()).reduce((sum, session) => sum + session.duration_seconds, 0); return { label: new Intl.DateTimeFormat('ru', { weekday: 'short' }).format(date), hours: seconds / 3600 }; }), [data.sessions]);
  const total = week.reduce((sum, item) => sum + item.hours, 0); const max = Math.max(1, ...week.map((item) => item.hours));
  const path = week.map((item, index) => `${index ? 'L' : 'M'} ${index * 48 + 8} ${128 - item.hours / max * 96}`).join(' ');
  const completedTasks = data.tasks.filter((task) => task.completed_at).length; const completedGoals = data.goals.filter((goal) => goal.status === 'completed').length;
  return <Screen><View style={styles.top}><Text style={[styles.eyebrow, { color: colors.textSecondary }]}>ПОСЛЕДНИЕ 7 ДНЕЙ</Text><Text accessibilityRole="header" style={[styles.title, { color: colors.text }]}>Аналитика</Text></View>
    <View style={[styles.segment, { backgroundColor: colors.surfaceSecondary }]}>{metrics.map((item) => <Pressable key={item} accessibilityRole="button" accessibilityState={{ selected: metric === item }} onPress={() => setMetric(item)} style={[styles.segmentItem, metric === item && { backgroundColor: colors.surface }]}><Text numberOfLines={1} style={[styles.segmentText, { color: metric === item ? colors.text : colors.textSecondary }]}>{item}</Text></Pressable>)}</View>
    {data.loading ? <ActivityIndicator color={colors.accent} style={styles.loader} /> : <>
      <View style={styles.hero}><Text style={[styles.heroLabel, { color: colors.textSecondary }]}>ВРЕМЯ В ФОКУСЕ</Text><Text style={[styles.heroValue, { color: colors.text }]}>{Math.floor(total)}ч {Math.round(total % 1 * 60)}м</Text><Text style={[styles.delta, { color: colors.accent }]}>{total > 0 ? 'Ваш недельный ритм' : 'Начните первую сессию'}</Text></View>
      <View style={[styles.chart, { backgroundColor: colors.surface, borderColor: colors.border }]}><Svg height={160} viewBox="0 0 304 160" width="100%"><Defs><LinearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><Stop offset="0" stopColor={colors.accent} stopOpacity="0.2" /><Stop offset="1" stopColor={colors.accent} stopOpacity="0" /></LinearGradient></Defs><Path d={`${path} L 296 148 L 8 148 Z`} fill="url(#fill)" /><Path d={path} fill="none" stroke={colors.accent} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /></Svg><View style={styles.labels}>{week.map((item) => <Text key={item.label} style={[styles.day, { color: colors.textSecondary }]}>{item.label}</Text>)}</View></View>
      <View style={styles.keyMetrics}><View><Text style={[styles.keyValue, { color: colors.text }]}>{completedTasks}</Text><Text style={[styles.keyLabel, { color: colors.textSecondary }]}>задач завершено</Text></View><View style={[styles.divider, { backgroundColor: colors.border }]} /><View><Text style={[styles.keyValue, { color: colors.text }]}>{data.sessions.length}</Text><Text style={[styles.keyLabel, { color: colors.textSecondary }]}>фокус-сессий</Text></View><View style={[styles.divider, { backgroundColor: colors.border }]} /><View><Text style={[styles.keyValue, { color: colors.text }]}>{completedGoals}</Text><Text style={[styles.keyLabel, { color: colors.textSecondary }]}>целей достигнуто</Text></View></View>
      <View style={[styles.insight, { borderTopColor: colors.border }]}><Text style={[styles.insightLabel, { color: colors.accent }]}>ИНСАЙТ</Text><Text style={[styles.insightText, { color: colors.text }]}>{total > 0 ? `За неделю вы защитили ${Math.round(total * 10) / 10} часа для важных дел. Стабильность важнее рекорда.` : 'Аналитика появится после первой завершённой фокус-сессии.'}</Text></View>
    </>}
  </Screen>;
}

const styles = StyleSheet.create({ top: { paddingTop: spacing.lg, paddingBottom: spacing.xl }, eyebrow: { fontSize: 12, fontWeight: '600' }, title: { fontSize: 38, lineHeight: 44, fontWeight: '600', marginTop: spacing.xs }, segment: { height: 42, borderRadius: radius.medium, padding: 3, flexDirection: 'row' }, segmentItem: { flex: 1, borderRadius: 6, alignItems: 'center', justifyContent: 'center' }, segmentText: { fontSize: 12, fontWeight: '500' }, loader: { marginTop: 120 }, hero: { marginTop: spacing.xxxl }, heroLabel: { fontSize: 12, fontWeight: '600' }, heroValue: { fontSize: 48, lineHeight: 56, fontWeight: '600', fontVariant: ['tabular-nums'], marginTop: spacing.xs }, delta: { fontSize: 14, fontWeight: '600', marginTop: spacing.xs }, chart: { marginTop: spacing.xl, borderWidth: StyleSheet.hairlineWidth, borderRadius: radius.medium, padding: spacing.md, paddingBottom: spacing.sm }, labels: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 2 }, day: { width: 36, fontSize: 11, textAlign: 'center', textTransform: 'capitalize' }, keyMetrics: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: spacing.xxxl }, keyValue: { fontSize: 22, fontWeight: '600', textAlign: 'center', fontVariant: ['tabular-nums'] }, keyLabel: { fontSize: 11, marginTop: spacing.xs, textAlign: 'center' }, divider: { width: StyleSheet.hairlineWidth, height: 42 }, insight: { marginTop: spacing.huge, borderTopWidth: StyleSheet.hairlineWidth, paddingTop: spacing.xl }, insightLabel: { fontSize: 12, fontWeight: '600' }, insightText: { fontSize: 18, lineHeight: 27, marginTop: spacing.sm } });
