import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ChevronLeft, ChevronRight, Plus } from 'lucide-react-native';
import { EmptyState, IconButton, Screen } from '@/components/ui';
import { useChronosData } from '@/features/app/useChronosData';
import { radius, spacing, useTheme } from '@/theme/tokens';

const week = ['ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ', 'ВС'];
const same = (a: Date, b: Date) => a.toDateString() === b.toDateString();
function monthDays(anchor: Date) { const first = new Date(anchor.getFullYear(), anchor.getMonth(), 1); const offset = (first.getDay() + 6) % 7; const start = new Date(first); start.setDate(first.getDate() - offset); return Array.from({ length: 42 }, (_, i) => { const day = new Date(start); day.setDate(start.getDate() + i); return day; }); }
export default function CalendarScreen() {
  const { colors } = useTheme(); const { tasks } = useChronosData(); const [anchor, setAnchor] = useState(new Date()); const [selected, setSelected] = useState(new Date()); const days = useMemo(() => monthDays(anchor), [anchor]); const selectedTasks = tasks.filter((task) => task.scheduled_at && same(new Date(task.scheduled_at), selected));
  const shift = (value: number) => setAnchor((date) => new Date(date.getFullYear(), date.getMonth() + value, 1));
  return <Screen><View style={styles.top}><View><Text style={[styles.eyebrow, { color: colors.textSecondary }]}>ВАШ РИТМ</Text><Text accessibilityRole="header" style={[styles.title, { color: colors.text }]}>Календарь</Text></View><IconButton icon={Plus} label="Добавить задачу" onPress={() => {}} /></View>
    <View style={styles.monthNav}><IconButton icon={ChevronLeft} label="Предыдущий месяц" onPress={() => shift(-1)} /><Text style={[styles.month, { color: colors.text }]}>{new Intl.DateTimeFormat('ru', { month: 'long', year: 'numeric' }).format(anchor)}</Text><IconButton icon={ChevronRight} label="Следующий месяц" onPress={() => shift(1)} /></View>
    <View style={styles.week}>{week.map((item) => <Text key={item} style={[styles.weekday, { color: colors.textSecondary }]}>{item}</Text>)}</View>
    <View style={styles.grid}>{days.map((day) => { const active = same(day, selected); const hasTask = tasks.some((task) => task.scheduled_at && same(new Date(task.scheduled_at), day)); const muted = day.getMonth() !== anchor.getMonth(); return <Pressable key={day.toISOString()} accessibilityRole="button" accessibilityState={{ selected: active }} onPress={() => setSelected(day)} style={styles.dayCell}><View style={[styles.dayCircle, active && { backgroundColor: colors.accent }]}><Text style={[styles.dayText, { color: active ? '#FFFFFF' : muted ? colors.textSecondary : colors.text }]}>{day.getDate()}</Text></View>{hasTask ? <View style={[styles.dot, { backgroundColor: active ? colors.text : colors.accent }]} /> : null}</Pressable>; })}</View>
    <View style={styles.agenda}><Text style={[styles.agendaDate, { color: colors.text }]}>{new Intl.DateTimeFormat('ru', { weekday: 'long', day: 'numeric', month: 'long' }).format(selected)}</Text>{selectedTasks.length ? selectedTasks.map((task) => <View key={task.id} style={[styles.event, { borderBottomColor: colors.border }]}><Text style={[styles.eventTime, { color: colors.textSecondary }]}>{new Intl.DateTimeFormat('ru', { hour: '2-digit', minute: '2-digit' }).format(new Date(task.scheduled_at!))}</Text><View style={[styles.eventMark, { backgroundColor: colors.accent }]} /><View style={styles.eventCopy}><Text style={[styles.eventTitle, { color: colors.text }]}>{task.title}</Text><Text style={[styles.eventDuration, { color: colors.textSecondary }]}>{task.duration_minutes} минут</Text></View></View>) : <EmptyState title="Свободное пространство" body="На этот день ничего не запланировано." />}</View>
  </Screen>;
}

const styles = StyleSheet.create({ top: { paddingTop: spacing.lg, paddingBottom: spacing.xxl, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, eyebrow: { fontSize: 12, fontWeight: '600' }, title: { fontSize: 38, lineHeight: 44, fontWeight: '600', marginTop: spacing.xs }, monthNav: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, month: { fontSize: 17, fontWeight: '600', textTransform: 'capitalize' }, week: { flexDirection: 'row', marginTop: spacing.xl }, weekday: { width: '14.2857%', textAlign: 'center', fontSize: 10, fontWeight: '600' }, grid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: spacing.sm }, dayCell: { width: '14.2857%', aspectRatio: 1, alignItems: 'center', justifyContent: 'center' }, dayCircle: { width: 36, height: 36, borderRadius: radius.full, alignItems: 'center', justifyContent: 'center' }, dayText: { fontSize: 14, fontVariant: ['tabular-nums'] }, dot: { width: 4, height: 4, borderRadius: 4, position: 'absolute', bottom: 5 }, agenda: { marginTop: spacing.xxxl }, agendaDate: { fontSize: 20, fontWeight: '600', textTransform: 'capitalize', marginBottom: spacing.md }, event: { minHeight: 72, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, eventTime: { width: 48, fontSize: 13, fontVariant: ['tabular-nums'] }, eventMark: { width: 3, height: 34, borderRadius: radius.full }, eventCopy: { flex: 1 }, eventTitle: { fontSize: 16, fontWeight: '500' }, eventDuration: { fontSize: 12, marginTop: 3 } });
