import { ActivityIndicator, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Plus } from 'lucide-react-native';
import { EmptyState, IconButton, PrimaryButton, Screen } from '@/components/ui';
import { ProgressRing } from '@/components/ProgressRing';
import { useChronosData } from '@/features/app/useChronosData';
import { radius, spacing, useTheme } from '@/theme/tokens';

const pct = (current: number, target: number) => target > 0 ? Math.min(100, current / target * 100) : 0;
const days = (due: string | null) => due ? Math.max(0, Math.ceil((new Date(due).getTime() - Date.now()) / 86400000)) : null;
export default function GoalsScreen() {
  const { colors } = useTheme(); const router = useRouter(); const { goals, loading, error } = useChronosData(); const active = goals.find((goal) => goal.status === 'active') ?? goals[0];
  return <Screen><View style={styles.top}><View><Text style={[styles.eyebrow, { color: colors.textSecondary }]}>НАПРАВЛЕНИЕ</Text><Text accessibilityRole="header" style={[styles.title, { color: colors.text }]}>Цели</Text></View><IconButton icon={Plus} label="Добавить цель" onPress={() => router.push('/new-goal')} /></View>
    {loading ? <ActivityIndicator color={colors.accent} style={styles.loader} /> : goals.length && active ? <>
      <View style={styles.featured}><Text style={[styles.featuredLabel, { color: colors.textSecondary }]}>ГЛАВНАЯ ЦЕЛЬ</Text><Text style={[styles.featuredTitle, { color: colors.text }]}>{active.title}</Text><View style={styles.featuredBody}><ProgressRing value={pct(active.current_value, active.target_value)} size={164} label="цели" /><View style={styles.featuredStats}><View><Text style={[styles.bigStat, { color: colors.text }]}>{active.current_value}<Text style={styles.unit}> / {active.target_value} {active.unit}</Text></Text><Text style={[styles.statLabel, { color: colors.textSecondary }]}>текущий результат</Text></View><View><Text style={[styles.pace, { color: colors.accent }]}>{days(active.due_date) === null ? 'Без срока' : `${days(active.due_date)} дней`}</Text><Text style={[styles.statLabel, { color: colors.textSecondary }]}>до контрольной даты</Text></View></View></View></View>
      <View style={styles.listSection}><Text style={[styles.listLabel, { color: colors.textSecondary }]}>ОСТАЛЬНЫЕ ЦЕЛИ</Text>{goals.filter((goal) => goal.id !== active.id).map((goal) => { const value = pct(goal.current_value, goal.target_value); return <View key={goal.id} style={[styles.row, { borderBottomColor: colors.border }]}><View style={styles.rowTop}><Text style={[styles.rowTitle, { color: colors.text }]}>{goal.title}</Text><Text style={[styles.rowValue, { color: colors.text }]}>{Math.round(value)}%</Text></View><View style={[styles.track, { backgroundColor: colors.surfaceSecondary }]}><View style={[styles.fill, { backgroundColor: colors.accent, width: `${value}%` }]} /></View><Text style={[styles.rowMeta, { color: colors.textSecondary }]}>{goal.status === 'completed' ? 'Выполнено' : days(goal.due_date) === null ? 'Активна · без срока' : `Активна · ${days(goal.due_date)} дней осталось`}</Text></View>; })}</View>
    </> : <EmptyState title="Цели ждут смысла" body="Создайте одну цель, ради которой вы готовы защищать время в календаре." action={<PrimaryButton label="Создать цель" icon={Plus} onPress={() => router.push('/new-goal')} />} />}
    {error ? <Text style={{ color: colors.danger }}>{error}</Text> : null}
  </Screen>;
}

const styles = StyleSheet.create({ top: { paddingTop: spacing.lg, paddingBottom: spacing.xxl, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, eyebrow: { fontSize: 12, fontWeight: '600' }, title: { fontSize: 38, lineHeight: 44, fontWeight: '600', marginTop: spacing.xs }, loader: { marginTop: 120 }, featured: { marginTop: spacing.md }, featuredLabel: { fontSize: 12, fontWeight: '600' }, featuredTitle: { fontSize: 28, lineHeight: 35, fontWeight: '600', marginTop: spacing.sm, maxWidth: 500 }, featuredBody: { marginTop: spacing.xxl, flexDirection: 'row', alignItems: 'center', gap: spacing.xxl, flexWrap: 'wrap' }, featuredStats: { gap: spacing.xl, flex: 1, minWidth: 160 }, bigStat: { fontSize: 28, fontWeight: '600', fontVariant: ['tabular-nums'] }, unit: { fontSize: 14, fontWeight: '400' }, statLabel: { fontSize: 12, marginTop: spacing.xs }, pace: { fontSize: 20, fontWeight: '600' }, listSection: { marginTop: spacing.huge }, listLabel: { fontSize: 12, fontWeight: '600', marginBottom: spacing.xs }, row: { paddingVertical: spacing.lg, borderBottomWidth: StyleSheet.hairlineWidth }, rowTop: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.md }, rowTitle: { fontSize: 16, lineHeight: 22, fontWeight: '500', flex: 1 }, rowValue: { fontSize: 15, fontWeight: '600', fontVariant: ['tabular-nums'] }, track: { height: 5, borderRadius: radius.full, overflow: 'hidden', marginTop: spacing.sm }, fill: { height: '100%', borderRadius: radius.full }, rowMeta: { fontSize: 12, marginTop: spacing.xs } });
