import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Check, Play, Plus, Settings2 } from 'lucide-react-native';
import * as Haptics from 'expo-haptics';
import { EmptyState, IconButton, PrimaryButton, Screen } from '@/components/ui';
import { ProgressRing } from '@/components/ProgressRing';
import { useChronosData } from '@/features/app/useChronosData';
import { requireSupabase } from '@/lib/supabase';
import { radius, spacing, useTheme } from '@/theme/tokens';

const isSameDay = (value: string | null, date: Date) => value ? new Date(value).toDateString() === date.toDateString() : false;
const time = (value: string | null) => value ? new Intl.DateTimeFormat('ru', { hour: '2-digit', minute: '2-digit' }).format(new Date(value)) : 'Без времени';
export default function TodayScreen() {
  const { colors } = useTheme(); const router = useRouter(); const data = useChronosData(); const now = new Date();
  const today = data.tasks.filter((task) => isSameDay(task.scheduled_at, now));
  const completed = today.filter((task) => task.completed_at).length; const progress = today.length ? completed / today.length * 100 : 0;
  const next = today.find((task) => !task.completed_at) ?? null;
  const complete = async (id: string) => { const { error } = await requireSupabase().from('tasks').update({ completed_at: new Date().toISOString() }).eq('id', id); if (!error) { await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); await data.reload(); } };
  return <Screen>
    <View style={styles.top}><View><Text style={[styles.eyebrow, { color: colors.textSecondary }]}>{new Intl.DateTimeFormat('ru', { weekday: 'long', day: 'numeric', month: 'long' }).format(now)}</Text><Text accessibilityRole="header" style={[styles.title, { color: colors.text }]}>Сегодня</Text></View><View style={styles.actions}><IconButton icon={Settings2} label="Настройки" onPress={() => router.push('/settings')} /><IconButton icon={Plus} label="Добавить задачу" onPress={() => router.push('/new-task')} /></View></View>
    {data.loading ? <ActivityIndicator color={colors.accent} style={styles.loader} /> : <>
      <View style={styles.progress}><ProgressRing value={progress} /><View style={styles.metrics}><View><Text style={[styles.metricValue, { color: colors.text }]}>{completed}/{today.length}</Text><Text style={[styles.metricLabel, { color: colors.textSecondary }]}>выполнено</Text></View><View><Text style={[styles.metricValue, { color: colors.text }]}>{today.reduce((sum, task) => sum + (task.completed_at ? task.duration_minutes : 0), 0)}м</Text><Text style={[styles.metricLabel, { color: colors.textSecondary }]}>в фокусе</Text></View><View><Text style={[styles.metricValue, { color: colors.text }]}>{Math.max(0, today.length - completed)}</Text><Text style={[styles.metricLabel, { color: colors.textSecondary }]}>осталось</Text></View></View></View>
      {data.error ? <Text style={[styles.error, { color: colors.danger }]}>{data.error}</Text> : null}
      {next ? <View style={styles.section}><Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>ДАЛЬШЕ</Text><View style={[styles.next, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.nextCopy}><Text style={[styles.nextTime, { color: colors.accent }]}>{time(next.scheduled_at)} · {next.duration_minutes} мин</Text><Text style={[styles.nextTitle, { color: colors.text }]}>{next.title}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Начать задачу" onPress={() => router.push({ pathname: '/(app)/timer', params: { task: next.id } })} style={[styles.play, { backgroundColor: colors.text }]}><Play size={20} color={colors.surface} fill={colors.surface} /></Pressable></View></View> : null}
      <View style={styles.section}><Text style={[styles.sectionLabel, { color: colors.textSecondary }]}>ПЛАН ДНЯ</Text>{today.length ? <View>{today.map((task) => <View key={task.id} style={[styles.task, { borderBottomColor: colors.border }]}><View style={styles.timeCol}><Text style={[styles.taskTime, { color: colors.textSecondary }]}>{time(task.scheduled_at)}</Text><Text style={[styles.duration, { color: colors.textSecondary }]}>{task.duration_minutes} мин</Text></View><Text numberOfLines={2} style={[styles.taskTitle, { color: task.completed_at ? colors.textSecondary : colors.text, textDecorationLine: task.completed_at ? 'line-through' : 'none' }]}>{task.title}</Text><Pressable accessibilityRole="checkbox" accessibilityState={{ checked: Boolean(task.completed_at) }} disabled={Boolean(task.completed_at)} onPress={() => complete(task.id)} style={[styles.check, { borderColor: task.completed_at ? colors.accent : colors.border, backgroundColor: task.completed_at ? colors.accent : 'transparent' }]}>{task.completed_at ? <Check size={14} color="#FFFFFF" /> : null}</Pressable></View>)}</View> : <EmptyState title="День свободен" body="Добавьте одно важное дело. Chronos оставит остальному достаточно воздуха." action={<PrimaryButton label="Добавить задачу" icon={Plus} onPress={() => router.push('/new-task')} />} />}</View>
      {today.length ? <View style={[styles.insight, { borderTopColor: colors.border }]}><Text style={[styles.insightLabel, { color: colors.accent }]}>НАБЛЮДЕНИЕ</Text><Text style={[styles.insightText, { color: colors.text }]}>{progress >= 70 ? 'Вы сохраняете хороший темп. Не заполняйте освободившееся время автоматически.' : 'Сосредоточьтесь на следующей задаче. Одного ясного шага сейчас достаточно.'}</Text></View> : null}
    </>}
  </Screen>;
}

const styles = StyleSheet.create({ top: { paddingTop: spacing.lg, paddingBottom: spacing.xxl, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { fontSize: 14, lineHeight: 20, textTransform: 'capitalize' }, title: { fontSize: 38, lineHeight: 44, fontWeight: '600', marginTop: 2 }, actions: { flexDirection: 'row', gap: spacing.xs }, loader: { marginTop: 120 }, progress: { alignItems: 'center', gap: spacing.xl, paddingVertical: spacing.md }, metrics: { width: '100%', flexDirection: 'row', justifyContent: 'space-around' }, metricValue: { fontSize: 20, fontWeight: '600', fontVariant: ['tabular-nums'], textAlign: 'center' }, metricLabel: { fontSize: 12, marginTop: 3, textAlign: 'center' }, error: { fontSize: 14, textAlign: 'center', marginTop: spacing.lg }, section: { marginTop: spacing.xxxl }, sectionLabel: { fontSize: 12, fontWeight: '600', marginBottom: spacing.sm }, next: { borderWidth: StyleSheet.hairlineWidth, borderRadius: radius.medium, padding: spacing.lg, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, nextCopy: { flex: 1 }, nextTime: { fontSize: 13, fontWeight: '600' }, nextTitle: { fontSize: 20, lineHeight: 26, fontWeight: '600', marginTop: spacing.xs }, play: { width: 48, height: 48, borderRadius: radius.full, alignItems: 'center', justifyContent: 'center' }, task: { minHeight: 72, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, timeCol: { width: 68 }, taskTime: { fontSize: 13, fontVariant: ['tabular-nums'] }, duration: { fontSize: 11, marginTop: 3 }, taskTitle: { flex: 1, fontSize: 16, lineHeight: 22 }, check: { width: 28, height: 28, borderRadius: radius.full, borderWidth: 1, alignItems: 'center', justifyContent: 'center' }, insight: { marginTop: spacing.huge, borderTopWidth: StyleSheet.hairlineWidth, paddingTop: spacing.xl }, insightLabel: { fontSize: 12, fontWeight: '600' }, insightText: { fontSize: 18, lineHeight: 27, marginTop: spacing.sm, maxWidth: 520 } });
