import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { ArrowLeft } from 'lucide-react-native';
import { Field, IconButton, PrimaryButton, Screen } from '@/components/ui';
import { requireSupabase } from '@/lib/supabase';
import { useAuth } from '@/providers/AuthProvider';
import { radius, spacing, useTheme } from '@/theme/tokens';

const nextHour = new Date();
nextHour.setHours(nextHour.getHours() + 1);
const defaultTime = new Intl.DateTimeFormat('ru', { hour: '2-digit', minute: '2-digit', hour12: false }).format(nextHour);

export default function NewTaskScreen() {
  const { colors } = useTheme(); const router = useRouter(); const { session } = useAuth(); const [title, setTitle] = useState(''); const [time, setTime] = useState(defaultTime); const [day, setDay] = useState<'today' | 'tomorrow'>('today'); const [duration, setDuration] = useState(45); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const save = async () => { if (!session || title.trim().length < 2) { setError('Добавьте короткое название задачи.'); return; } const match = /^(\d{1,2}):(\d{2})$/.exec(time.trim()); if (!match) { setError('Введите время в формате 09:30.'); return; } const date = new Date(); if (day === 'tomorrow') date.setDate(date.getDate() + 1); date.setHours(Number(match[1]), Number(match[2]), 0, 0); setLoading(true); const { error: saveError } = await requireSupabase().from('tasks').insert({ user_id: session.user.id, title: title.trim(), scheduled_at: date.toISOString(), duration_minutes: duration }); if (saveError) { setError('Не удалось сохранить задачу.'); setLoading(false); return; } router.back(); };
  return <Screen><View style={styles.header}><IconButton icon={ArrowLeft} label="Закрыть" onPress={() => router.back()} /></View><Text style={[styles.title, { color: colors.text }]}>Новое дело</Text><Text style={[styles.subtitle, { color: colors.textSecondary }]}>Сначала главное. Дополнительные детали можно добавить позже.</Text><View style={styles.form}><Field label="Что важно сделать?" value={title} onChangeText={setTitle} autoFocus returnKeyType="next" /><View><Text style={[styles.label, { color: colors.text }]}>День</Text><View style={[styles.segment, { backgroundColor: colors.surfaceSecondary }]}>{[['today', 'Сегодня'], ['tomorrow', 'Завтра']].map(([value, label]) => <Pressable key={value} onPress={() => setDay(value as typeof day)} style={[styles.segmentItem, day === value && { backgroundColor: colors.surface }]}><Text style={{ color: day === value ? colors.text : colors.textSecondary, fontWeight: '500' }}>{label}</Text></Pressable>)}</View></View><Field label="Время" value={time} onChangeText={setTime} keyboardType="numbers-and-punctuation" placeholder="09:30" /><View><Text style={[styles.label, { color: colors.text }]}>Продолжительность</Text><View style={styles.chips}>{[25, 45, 60].map((value) => <Pressable key={value} onPress={() => setDuration(value)} style={[styles.chip, { borderColor: duration === value ? colors.accent : colors.border, backgroundColor: duration === value ? colors.accentSoft : colors.surface }]}><Text style={{ color: duration === value ? colors.accent : colors.text }}>{value} мин</Text></Pressable>)}</View></View>{error ? <Text style={{ color: colors.danger }}>{error}</Text> : null}<PrimaryButton label="Добавить в день" loading={loading} onPress={save} /></View></Screen>;
}
const styles = StyleSheet.create({ header: { paddingTop: spacing.md }, title: { fontSize: 36, lineHeight: 42, fontWeight: '600', marginTop: spacing.xl }, subtitle: { fontSize: 16, lineHeight: 24, marginTop: spacing.sm }, form: { marginTop: spacing.huge, gap: spacing.xl }, label: { fontSize: 14, fontWeight: '500', marginBottom: spacing.xs }, segment: { height: 48, padding: 3, borderRadius: radius.medium, flexDirection: 'row' }, segmentItem: { flex: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 6 }, chips: { flexDirection: 'row', gap: spacing.sm }, chip: { minWidth: 76, minHeight: 44, borderRadius: radius.full, borderWidth: StyleSheet.hairlineWidth, alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.md } });
